apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend
  labels:
    app: ecommerce
    tier: frontend
spec:
  type: NodePort
  selector:
    app: ecommerce
    tier: frontend
  ports:
    - port: 80       # cluster port (clients will use this)
      targetPort: 3000
      protocol: TCP
      name: http
